#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: mah-lab-cedar
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
    TZ: "Asia/Tokyo"

staging:
  app: mah-lab-cedar-staging
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test"
    TZ: "Asia/Tokyo"

